program = { env = "AUREUM_TEST_BASH" }
program_arguments = ["helpers/absolute-path.sh"]

expected_stdout = """
🚀 Running 1 tests:
.

✅ helpers/dir1/test1.toml

Test result: OK (1 passed, 0 failed)
"""
expected_stderr = ""
expected_exit_code = 0
