test_program = { env = "AUREUM_EXEC" }
test_arguments = [
  "helpers/dir1/*.toml",
  "helpers/dir2/*.toml",
  "helpers/dir1/*.toml", # This argument is redundant, but it tests that the paths are deduplicated.
]

expected_stdout = """
✅ ./helpers/dir1/test1.toml
✅ ./helpers/dir1/test2.toml
✅ ./helpers/dir2/test1.toml
✅ ./helpers/dir2/test2.toml

Completed running 4 tests.
All tests passed.
"""
expected_stderr = ""
expected_exit_code = 0
