test_program = { env = "AUREUM_EXEC" }
test_arguments = [
  "multiple-dirs1/*.toml",
  "multiple-dirs2/*.toml",
  "multiple-dirs1/*.toml", # This argument is redundant, but it tests that the paths are deduplicated.
]

expected_stdout = """
✅ ./multiple-dirs1/test1.toml
✅ ./multiple-dirs1/test2.toml
✅ ./multiple-dirs2/test1.toml
✅ ./multiple-dirs2/test2.toml

Completed running 4 tests.
All tests passed.
"""
expected_stderr = ""
expected_exit_code = 0
