test_program = { env = "AUREUM_EXEC" }
test_arguments = ["multiple-files1.toml", "multiple-files2.toml"]

expected_stdout = """
✅ ./multiple-files1.toml
✅ ./multiple-files2.toml

Completed running 2 tests.
All tests passed.
"""
expected_stderr = ""
expected_exit_code = 0
