test_program = { env = "AUREUM_EXEC" }
test_arguments = ["single-dir/*.toml"]

expected_stdout = """
✅ ./single-dir/test1.toml
✅ ./single-dir/test2.toml

Completed running 2 tests.
All tests passed.
"""
expected_stderr = ""
expected_exit_code = 0
