test_program = { env = "AUREUM_EXEC" }
test_arguments = ["single-file.toml"]

expected_stdout = """
✅ ./single-file.toml

Completed running 1 tests.
All tests passed.
"""
expected_stderr = ""
expected_exit_code = 0
