test_program = { env = "AUREUM_EXEC" }
test_arguments = ["helpers/dir1/test1.toml"]

expected_stdout = """
✅ ./helpers/dir1/test1.toml

Completed running 1 tests.
All tests passed.
"""
expected_stderr = ""
expected_exit_code = 0
