test_program = { env = "AUREUM_EXEC" }
test_arguments = ["helpers/dir1/*.toml"]

expected_stdout = """
✅ ./helpers/dir1/test1.toml
✅ ./helpers/dir1/test2.toml

Completed running 2 tests.
All tests passed.
"""
expected_stderr = ""
expected_exit_code = 0
