# program = "echo" # This should produce an error in both test cases below:


[tests.test1]
program_arguments = ["-n", "Test 1"]
expected_stdout = "Test 1"


[tests.test2]
program_arguments = ["-n", "Test 2"]
expected_stdout = "Test 2"
