test_program = { env = "AUREUM_EXEC" }
test_arguments = ["single-dir/*.toml"]

expected_stdout = """
TAP version 14
1..2
ok 1 - test1 [./single-dir/test1.toml]
ok 2 - test2 [./single-dir/test2.toml]
"""
expected_stderr = ""
expected_exit_code = 0
