test_program = { env = "AUREUM_EXEC" }
test_arguments = ["single-file.toml"]

expected_stdout = """
TAP version 14
1..1
ok 1 - single-file [./single-file.toml]
"""
expected_stderr = ""
expected_exit_code = 0
