test_program = { env = "AUREUM_EXEC" }
test_arguments = ["test-multiple-files1.toml", "test-multiple-files2.toml"]

expected_stdout = """
TAP version 14
1..2
ok 1 - test-multiple-files1 [./test-multiple-files1.toml]
ok 2 - test-multiple-files2 [./test-multiple-files2.toml]
"""
