test_program = { env = "AUREUM_TEST_EXEC" }
test_arguments = ["--help"]

expected_stdout = """
Golden test runner for executables

Usage: aureum [OPTIONS] <PATHS>...

Arguments:
  <PATHS>...  Paths to test configs

Options:
      --output-format <OUTPUT_FORMAT>  Options: summary, tap [default: summary]
      --show-all-tests                 Show all tests in summary, regardless of test status
      --run-tests-in-parallel          Run tests in parallel
  -h, --help                           Print help information
"""
