program = { env = "AUREUM_TEST_EXEC" }
program_arguments = ["--help"]

expected_stdout = """
Golden test runner for executables

Usage: aureum [OPTIONS] <PATHS>...

Arguments:
  <PATHS>...  Paths to config files

Options:
      --output-format <OUTPUT_FORMAT>  Options: summary, tap [default: summary]
      --show-all-tests                 Show all tests in summary, regardless of test status
      --hide-absolute-paths            Replace absolute paths with a platform-independent placeholder
      --run-tests-in-parallel          Run tests in parallel
      --verbose                        Print extra information about config files
  -h, --help                           Print help information
"""
