test_program = { env = "AUREUM_EXEC" }
test_arguments = ["--help"]

expected_stdout = """
Golden test runner

Usage: aureum [OPTIONS] <PATHS>...

Arguments:
  <PATHS>...  Paths to test configs

Options:
      --output-format <OUTPUT_FORMAT>  Options: summary, tap [default: summary]
  -h, --help                           Print help information
"""
