program = { env = "AUREUM_TEST_EXEC" }
program_arguments = [
  "--run-tests-in-parallel",
  "basic-helpers/passing-test.toml",
  "basic-helpers/passing-test2.toml",
]

expected_stdout = """
🚀 Running 2 tests:
..

Test result: OK (2 passed, 0 failed)
"""
expected_stderr = ""
expected_exit_code = 0
