test_program = { env = "AUREUM_TEST_EXEC" }
test_arguments = [
  "--run-tests-in-parallel",
  "helpers/passing-test.toml",
  "helpers/passing-test2.toml",
]

expected_stdout = """
Started running 2 tests:
..

Finished running tests: 2 passed, 0 failures
"""
expected_stderr = ""
expected_exit_code = 0
