test_program = { env = "AUREUM_EXEC" }
test_arguments = []

expected_stderr = """
error: The following required arguments were not provided:
  <PATH>

Usage: aureum <PATH>

For more information try '--help'
"""
