test_program = { env = "AUREUM_EXEC" }
test_arguments = []

expected_stderr = """
error: The following required arguments were not provided:
  <PATHS>...

Usage: aureum <PATHS>...

For more information try '--help'
"""
