program = "echo"
program_arguments = ["-n", "Hello world"]

[tests.env-var-exists]
expected_stdout = { env = "AUREUM_TEST_HELLO_WORLD" }

[tests.env-var-missing]
expected_stdout = { env = "AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST" }

[tests.external-file-exists]
expected_stdout = { file = "hello-world.txt" }

[tests.external-file-missing]
expected_stdout = { file = "aureum-test-file-does-not-exist" }
